version: 2
jobs:
  build:
    working_directory: ~/circleci-test-ruby

    # Primary container image where all commands run

    docker:
      - image: circleci/ruby:2.4.1-node

    steps:
      - checkout

      - run:
          name: Parallel RSpec
          command: bin/rspec